[RunControl]
dataproducers  = ALPIDE_plane_0
moreproducers  = POWER_0,POWER_1,PTH_0,TRIGGER_0,ZABER_0,ZABER_1
loggers     = log
collectors  = dc
configs     = /home/palpidefs/chun/zaber_dryrun.conf

[LibraryPaths]
trigger_path = /home/palpidefs/testbeam/trigger/software/

[LogCollector.log]
FILE_PATTERN = ./errorlog/EUDAQLog$12D.log
# 0: DEBUG, 4: INFO, 5: WARN, 6: ERROR
LOG_LEVEL_WRITE = 0
LOG_LEVEL_PRINT = 1

[DataCollector.dc]
dataproducers = ALPIDE_plane_0

[Producer.TRIGGER_0]
port = auto # or /dev/serial/by-id/whatever_is_the_board_name
# MCP configuration (important)
CH0_GAIN = 0.8
CH3_GAIN = 0.8
CH0_THR  = 1.0
CH3_THR  = 1.0
# Spill counter configuration (fancy stuff)
spill_counter_sampling_period_s = 180 # seconds
spill_counter_threshold = 5 # noise suppresion (min. number of counts to consider it a spill)
# Advanced:
# spill_counter_bucket_size_ms = 2000
# spill_counter_spill_separation = 3

[Producer.POWER_0]
path        = /dev/PS_ALPIDE_TRG

[Producer.POWER_1]
path        = /dev/PS_USB_MOSS

[Producer.ALPIDE_plane_0]
serial      = DAQ-0009012905D1233D 
plane       = 0
triggermode = replica

[Producer.ZABER_0]
serial_path = /dev/ZABER_D
config_path = /home/palpidefs/testbeam/eudaq2/user/ITS3/misc/zaber/zaberconf_downstream.json
# config_path = /home/palpidefs/testbeam/eudaq2/user/ITS3/misc/conf_examples/zaber/zaberconf.json

[Producer.ZABER_1]
serial_path = /dev/ZABER_U
config_path = /home/palpidefs/testbeam/eudaq2/user/ITS3/misc/zaber/zaberconf_upstream.json
# config_path = /home/palpidefs/testbeam/eudaq2/user/ITS3/misc/conf_examples/zaber/zaberconf.json
