[RunControl]
EUDAQ_CTRL_PRODUCER_LAST_START = ALPIDE_plane_0 # this is the one with the trigger primary
EUDAQ_CTRL_PRODUCER_FIRST_STOP = ALPIDE_plane_0
NEVENTS = 100

[Producer.TRIGGER_0]
EUDAQ_DC  = dc
trg = trg0&trg3&dt_trg>10000&dt_veto>5000 & !bsy
#trg0&trg3&dt_trg>10000&dt_veto>5000 & !bsy

veto = ntrg>0
count = 1xxR Rxx1 xxxR Rxxx # trigger conditions to count, first one taken as input for spill counter
read_interval = 2 # seconds

[Producer.PTH_0]
EUDAQ_DC  = dc

[Producer.ZABER_0]
EUDAQ_DC  = dc
set_pos_zaber_downstream_x = 3000 # set_pos_AXISALIAS = VALUE (absolute positon in um or degrees)
set_pos_zaber_downstream_y = 1000


[Producer.ZABER_1]
EUDAQ_DC  = dc
set_pos_zaber_upstream_x = 1997 # set_pos_AXISALIAS = VALUE (absolute positon in um or degrees)
set_pos_zaber_upstream_y = 2046


[Producer.POWER_0]
EUDAQ_DC  = dc
#voltage_#CHANNEL NUMBER#  = VOLTAGE  #change voltage of a specific channel of the connected power supply (HMP4040) before the start of the run
#current_#CHANNEL NUMBER#  = CURRENT  #change current of a specific channel of the connected power supply (HMP4040) before the start of the run

[Producer.POWER_1]
EUDAQ_DC  = dc
#voltage_#CHANNEL NUMBER#  = VOLTAGE  #change voltage of a specific channel of the connected power supply (HMP4040) before the start of the run
#current_#CHANNEL NUMBER#  = CURRENT  #change current of a specific channel of the connected power supply (HMP4040) before the start of the run

[Producer.ALPIDE_plane_0]
EUDAQ_DC      = dc
EUDAQ_ID      = 0
ITHR          = 60
VCASN         = 109
VCASN2        = 121
VCLIP         = 60
IDB           = 29
STROBE_LENGTH = 160


[DataCollector.dc]
EUDAQ_FW = native
EUDAQ_FW_PATTERN = /data/testbeam/dryrun/zaber_run$6R_$12D$X
